ci/all: Init an `all` check, that checks all steps

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -93,6 +93,20 @@ jobs:
           diagnostic-endpoint: ""
       - name: "build devshells"
         run: nix build .#devShells.${{ matrix.system }}.default -Lvv --no-update-lock-file
+  all:
+    name: All checks passed
+    if: always()
+    runs-on: ubuntu-latest
+    needs: ['formatting', 'scoutty', 'devshells']
+    steps:
+      - name: "verify all jobs passed"
+        run: |
+          if [[ "${{ needs.formatting.result }}" != "success" ]] || \
+             [[ "${{ needs.scoutty.result }}" != "success" ]] || \
+             [[ "${{ needs.devshells.result }}" != "success" ]]; then
+            echo "Some checks failed"
+            exit 1
+          fi
   release:
     if: startsWith(github.ref, 'refs/tags/v')
     runs-on: ubuntu-latest
